### ISSUE TITLE
Variable sizes

### ISSUE THREAD

**Issue by grotrek** [quarkslab/sspam#10]
Hello.
I am trying to use your tool, and have one question.
How can I specify sizes? For example:
sspam "x + 10 + 15" returns (x + 9), but I want to see (x + 25). Is it any way to do this?

**Comment by noutoff** [comment]
Hello,
Sorry for the (very) late reply. This is because sspam infers the number of bits from the size of your constants (10 and 15 being under 16, they can be written on 4 bits). You can force the size with:

`sspam -n 32 "x + 10 + 15"`

if you want the result on 32 bits for example.
